"""AI Vendor Recommendation (Phase 9D).

Given an item_id (or pr_id with multiple items), return the top-3 vendors
ranked by a weighted score:
    price 40% · lead_time 20% · scorecard 30% · recency 10%

For each candidate vendor we aggregate from `goods_receipts` + `purchase_orders`:
    - avg / last unit cost
    - lead time (days from PO creation → GR receipt)
    - frequency (number of receipts)
    - last receipt date
    - vendor scorecard (Phase 9B) when present
    - rationale (1 sentence Bahasa Indonesia, generated by Gemini 2.5 Flash)

The LLM rationale is non-blocking: if the call fails, returns a deterministic
fallback rationale based on the metrics.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Optional

from core.config import settings
from core.db import get_db
from core.runtime_config import get_setting

logger = logging.getLogger("aurora.ai_vendor")

# Weights (sum to 1.0)
W_PRICE = 0.40
W_LEAD = 0.20
W_SCORE = 0.30
W_RECENCY = 0.10


def _safe_float(v, default: float = 0.0) -> float:
    try:
        return float(v) if v is not None else default
    except Exception:  # noqa: BLE001
        return default


def _days_between(d1: str, d2: str) -> Optional[float]:
    """Both ISO date strings (YYYY-MM-DD or full ISO). Returns abs day delta."""
    try:
        a = datetime.fromisoformat(str(d1)[:10])
        b = datetime.fromisoformat(str(d2)[:10])
        return abs((b - a).days)
    except Exception:  # noqa: BLE001
        return None


async def _aggregate_vendor_stats(item_id: str) -> dict[str, dict]:
    """Returns map vendor_id → stats {avg_cost, last_cost, lead_time_avg, recency_days, gr_count, last_date}."""
    db = get_db()
    # 1) Pull all GR lines for this item where parent GR is posted
    pipeline = [
        {"$match": {"deleted_at": None, "status": "posted", "lines.item_id": item_id}},
        {"$unwind": "$lines"},
        {"$match": {"lines.item_id": item_id}},
        {"$project": {
            "_id": 0,
            "vendor_id": 1,
            "po_id": 1,
            "receive_date": 1,
            "unit_cost": "$lines.unit_cost",
            "qty": "$lines.qty_received",
        }},
    ]
    rows: list[dict] = []
    async for r in db.goods_receipts.aggregate(pipeline):
        rows.append(r)
    if not rows:
        return {}

    # 2) For each PO referenced, pull `created_at` (or order_date) for lead time
    po_ids = sorted({r["po_id"] for r in rows if r.get("po_id")})
    po_date_by_id: dict[str, str] = {}
    if po_ids:
        async for po in db.purchase_orders.find(
            {"id": {"$in": po_ids}}, {"id": 1, "order_date": 1, "created_at": 1},
        ):
            po_date_by_id[po["id"]] = po.get("order_date") or po.get("created_at", "")[:10]

    # 3) Group by vendor
    today_iso = datetime.now(timezone.utc).date().isoformat()
    by_vendor: dict[str, dict] = {}
    for r in rows:
        vid = r.get("vendor_id")
        if not vid:
            continue
        bucket = by_vendor.setdefault(vid, {
            "costs": [],
            "lead_times": [],
            "receive_dates": [],
            "qtys": [],
        })
        bucket["costs"].append(_safe_float(r.get("unit_cost")))
        bucket["qtys"].append(_safe_float(r.get("qty")))
        recv = r.get("receive_date")
        if recv:
            bucket["receive_dates"].append(str(recv)[:10])
        po_date = po_date_by_id.get(r.get("po_id"))
        if po_date and recv:
            lt = _days_between(po_date, str(recv)[:10])
            if lt is not None and 0 <= lt <= 90:
                bucket["lead_times"].append(lt)

    out: dict[str, dict] = {}
    for vid, b in by_vendor.items():
        costs = [c for c in b["costs"] if c > 0]
        avg_cost = sum(costs) / len(costs) if costs else 0
        # last cost = associated with latest receive date
        last_cost = costs[-1] if costs else 0
        lead_avg = sum(b["lead_times"]) / len(b["lead_times"]) if b["lead_times"] else None
        last_date = max(b["receive_dates"]) if b["receive_dates"] else None
        recency = _days_between(last_date, today_iso) if last_date else None
        out[vid] = {
            "avg_cost": round(avg_cost, 2),
            "last_cost": round(last_cost, 2),
            "lead_time_avg": round(lead_avg, 2) if lead_avg is not None else None,
            "recency_days": int(recency) if recency is not None else None,
            "gr_count": len(b["costs"]),
            "total_qty": round(sum(b["qtys"]), 2),
            "last_receive_date": last_date,
        }
    return out


async def _vendor_scorecards(vendor_ids: list[str]) -> dict[str, float]:
    """Return map vendor_id → scorecard_score (0-5 scale) using existing scorecard service if present."""
    if not vendor_ids:
        return {}
    db = get_db()
    out: dict[str, float] = {}
    # Quick-and-safe: read from `vendor_scorecards` if it exists
    try:
        coll_names = await db.list_collection_names()
        if "vendor_scorecards" in coll_names:
            async for s in db.vendor_scorecards.find(
                {"vendor_id": {"$in": vendor_ids}},
                {"vendor_id": 1, "overall_score": 1, "score": 1},
            ):
                val = s.get("overall_score") or s.get("score") or 0
                out[s["vendor_id"]] = _safe_float(val)
    except Exception as e:  # noqa: BLE001
        logger.warning(f"vendor_scorecards lookup failed: {e}")
    return out


def _normalize(values: list[float], invert: bool = False) -> list[float]:
    """0..1 normalized. invert=True → lower is better (good for price/lead-time)."""
    if not values:
        return []
    lo, hi = min(values), max(values)
    if hi == lo:
        return [1.0 for _ in values]
    if invert:
        return [(hi - v) / (hi - lo) for v in values]
    return [(v - lo) / (hi - lo) for v in values]


async def _generate_rationale(item_name: str, vendor_name: str, stats: dict, score: float) -> str:
    """Generate a 1-sentence Indonesian rationale via Gemini 2.5 Flash.

    Falls back to a deterministic message if LLM unavailable.
    """
    fallback = (
        f"{vendor_name}: harga rata-rata Rp {int(stats.get('avg_cost', 0)):,}".replace(",", ".")
        + (
            f", lead time {stats.get('lead_time_avg', 0):.1f} hari"
            if stats.get("lead_time_avg") is not None else ""
        )
        + f", {stats.get('gr_count', 0)} riwayat pembelian."
    )

    llm_key = await get_setting("EMERGENT_LLM_KEY", default=settings.emergent_llm_key)
    if not settings.feature_ai_enabled or not llm_key:
        return fallback

    try:
        from emergentintegrations.llm.chat import LlmChat, UserMessage
        sys = (
            "You explain why a vendor is recommended for an Indonesian F&B procurement. "
            "Write ONE concise sentence in Bahasa Indonesia (max 22 words). "
            "No preamble, no JSON, no markdown."
        )
        prompt = (
            f"Item: {item_name}\n"
            f"Vendor: {vendor_name}\n"
            f"Avg cost: Rp {int(stats.get('avg_cost', 0)):,}\n"
            f"Last cost: Rp {int(stats.get('last_cost', 0)):,}\n"
            f"Lead time avg: {stats.get('lead_time_avg', 'N/A')} hari\n"
            f"Riwayat GR: {stats.get('gr_count', 0)}\n"
            f"Recency: {stats.get('recency_days', 'N/A')} hari lalu\n"
            f"Composite score: {score:.2f}/1.0\n"
        ).replace(",", ".")
        chat = LlmChat(
            api_key=llm_key,
            session_id=f"vrec-{vendor_name[:10]}",
            system_message=sys,
        ).with_model("gemini", "gemini-2.5-flash")
        resp = await chat.send_message(UserMessage(text=prompt))
        resp = (resp or "").strip()
        if 4 < len(resp) < 400:
            return resp
        return fallback
    except Exception as e:  # noqa: BLE001
        logger.warning(f"rationale gen failed for {vendor_name}: {e}")
        return fallback


async def recommend_for_item(
    item_id: str, *, top_k: int = 3, generate_rationale: bool = True,
) -> dict:
    """Return top-K vendors for the given item_id with metrics + rationale.

    Returns:
      {
        "item_id": "...",
        "item_name": "...",
        "candidates": [
          {
            "vendor_id", "vendor_name", "score" (0-1),
            "metrics": {
              "avg_cost", "last_cost", "lead_time_avg",
              "recency_days", "gr_count", "scorecard"
            },
            "rationale": "<1 sentence>"
          },
          ...
        ],
        "weights": {...},
        "computed_at": ISO,
      }
    """
    db = get_db()
    # Resolve item
    item = await db.items.find_one({"id": item_id, "deleted_at": None})
    if not item:
        return {"item_id": item_id, "error": "item not found", "candidates": []}

    stats_by_vendor = await _aggregate_vendor_stats(item_id)
    if not stats_by_vendor:
        return {
            "item_id": item_id, "item_name": item.get("name"),
            "candidates": [], "weights": _weights_dict(),
            "computed_at": datetime.now(timezone.utc).isoformat(),
            "note": "Belum ada riwayat GR untuk item ini.",
        }

    vendor_ids = list(stats_by_vendor.keys())
    name_by_id: dict[str, str] = {}
    async for v in db.vendors.find({"id": {"$in": vendor_ids}}, {"id": 1, "name": 1}):
        name_by_id[v["id"]] = v.get("name", "")

    scorecard_by_id = await _vendor_scorecards(vendor_ids)

    # Build numeric vectors for normalization
    avg_costs = [s.get("avg_cost", 0) or 0 for s in stats_by_vendor.values()]
    leads = [s.get("lead_time_avg") or 999 for s in stats_by_vendor.values()]
    recencies = [s.get("recency_days") if s.get("recency_days") is not None else 999
                 for s in stats_by_vendor.values()]
    scorecards = [scorecard_by_id.get(vid, 0.0) for vid in vendor_ids]

    n_costs = _normalize(avg_costs, invert=True)
    n_leads = _normalize(leads, invert=True)
    n_recency = _normalize(recencies, invert=True)
    # scorecard: assume 0..5 scale, divide by 5
    n_scorecard = [min(max(sc / 5.0, 0.0), 1.0) for sc in scorecards]

    candidates = []
    for i, vid in enumerate(vendor_ids):
        score = (
            W_PRICE * n_costs[i]
            + W_LEAD * n_leads[i]
            + W_SCORE * n_scorecard[i]
            + W_RECENCY * n_recency[i]
        )
        candidates.append({
            "vendor_id": vid,
            "vendor_name": name_by_id.get(vid, "—"),
            "score": round(score, 4),
            "metrics": {
                **stats_by_vendor[vid],
                "scorecard": scorecards[i],
            },
        })
    candidates.sort(key=lambda x: x["score"], reverse=True)
    top = candidates[: max(1, min(top_k, 5))]

    if generate_rationale:
        for c in top:
            c["rationale"] = await _generate_rationale(
                item.get("name", ""), c["vendor_name"], c["metrics"], c["score"],
            )

    return {
        "item_id": item_id,
        "item_name": item.get("name"),
        "candidates": top,
        "weights": _weights_dict(),
        "total_candidates_seen": len(candidates),
        "computed_at": datetime.now(timezone.utc).isoformat(),
    }


async def recommend_for_pr(pr_id: str, *, top_k: int = 3) -> dict:
    """Return per-line vendor recommendations for a PR's items."""
    db = get_db()
    pr = await db.purchase_requests.find_one({"id": pr_id, "deleted_at": None})
    if not pr:
        return {"pr_id": pr_id, "error": "PR not found", "lines": []}

    out_lines = []
    for ln in pr.get("lines", []) or []:
        item_id = ln.get("item_id")
        if not item_id:
            out_lines.append({
                "item_name": ln.get("item_name"), "item_id": None,
                "candidates": [], "note": "item belum di-master",
            })
            continue
        rec = await recommend_for_item(item_id, top_k=top_k, generate_rationale=False)
        out_lines.append({
            "item_id": item_id,
            "item_name": ln.get("item_name") or rec.get("item_name"),
            "candidates": rec.get("candidates", []),
        })

    # Aggregate: which vendor appears in top-1 most often?
    top1_count: dict[str, int] = {}
    top1_name: dict[str, str] = {}
    for ln in out_lines:
        if ln["candidates"]:
            top = ln["candidates"][0]
            top1_count[top["vendor_id"]] = top1_count.get(top["vendor_id"], 0) + 1
            top1_name[top["vendor_id"]] = top["vendor_name"]

    consensus = sorted(
        [{"vendor_id": v, "vendor_name": top1_name[v], "wins": c} for v, c in top1_count.items()],
        key=lambda x: x["wins"], reverse=True,
    )

    return {
        "pr_id": pr_id,
        "pr_doc_no": pr.get("doc_no"),
        "lines": out_lines,
        "consensus": consensus[:3],
        "computed_at": datetime.now(timezone.utc).isoformat(),
    }


def _weights_dict() -> dict:
    return {"price": W_PRICE, "lead_time": W_LEAD, "scorecard": W_SCORE, "recency": W_RECENCY}
