/** Tour registry, versions, and helper. All imports from domain sub-files. */

import {
  outletHomeTour,
  outletDailyOrdersHubTour,
  outletEndOfDayWorkflowTour,
  outletCRMHubTour,
  outletReservationListTour,
  outletReservationFormTour,
  outletDailySalesTour,
  outletSalesWizardTour,
  outletDailyCloseTour,
  outletPettyCashTour,
  outletLoyaltyScanTour,
  outletUrgentPurchaseTour,
  outletBudgetTrackerTour,
  outletStockCheckTour,
  outletStockTransfersTour,
  outletUsageLogTour,
  outletLoyaltyPointsTour,
} from './outlet';
import {
  adminHomeTour,
  adminAuditLogTour,
  adminMasterDataHubTour,
  adminCMSStudioTour,
  adminMenuCMSTour,
  adminUsersTour,
  adminRolesTour,
  adminApprovalBuilderTour,
  adminWorkflowsTour,
  adminBulkImportTour,
  adminNumberSeriesTour,
  adminTaxConfigTour,
  adminOperationsTour,
  adminSettingsTour,
  adminLoyaltyOverviewTour,
  adminLoyaltyCustomersTour,
  adminLoyaltyRewardsTour,
  adminConfigurationTour,
  adminReportSchedulesTour,
  adminDataManagementTour,
  adminSmartSEOTour,
  adminIntegrationsTour,
  adminTourAnalyticsTour,
  adminUserManagementHubTour,
  adminSetupHubTour,
  adminEffectiveDatingTour,
  adminLoyaltyRedemptionsTour,
} from './admin';
import {
  procurementHomeTour,
  procurementKanbanTour,
  procurementPRListTour,
  procurementPOListTour,
  procurementGRTour,
  procurementVendorCompareTour,
  procurementVendorsTour,
  procurementVendorScorecardTour,
  procurementVendorRecommendTour,
  procurementRFQTour,
  procurementConsolidationTour,
  procurementPOComparisonTour,
  procurementPriceIntelligenceTour,
  procurementVendorCatalogTour,
} from './procurement';
import {
  financeHomeTour,
  financeValidationTour,
  financeManualJournalTour,
  financeAPTour,
  financeJournalsTour,
  financePaymentRequestsTour,
  financePaymentsTour,
  financeBankReconTour,
  financeARInvoicesTour,
  financeTrialBalanceTour,
  financeBalanceSheetTour,
  financeCashflowTour,
  financeCOATour,
  financeProfitLossTour,
  financeAnomaliesTour,
  financeComparativesTour,
  financePeriodsLockingTour,
  financePeriodClosingHubTour,
  financePaymentsHubTour,
  financeReportsHubTour,
  financeTaxHubTour,
  financeBudgetHubTour,
  financeAssetsTour,
  financeCashPositionTour,
  financeVendorScorecardTour,
  financeReservationDepositsTour,
  financePaymentRunsTour,
  financePaymentRunTemplatesTour,
  financeForecastingTour,
  financeBudgetVsActualTour,
  financeEFakturTour,
  financeEBupotTour,
} from './finance';
import {
  inventoryHomeTour,
  inventoryBalanceTour,
  inventoryMovementsTour,
  inventoryOpnameTour,
  inventoryTransfersTour,
  inventoryAdjustmentTour,
  inventoryMovementsHubTour,
  inventoryLowStockTour,
  inventoryMarketListTour,
  inventoryValuationTour,
} from './inventory';
import {
  executiveHomeTour,
  executiveOwnerHomeTour,
  executiveOutletDrilldownTour,
  executiveBrandDrilldownTour,
  executiveAIQATour,
  executiveAnomalyTour,
  executiveBrandMixTour,
  executiveProfitWalkTour,
  executivePeriodCompareTour,
  executiveAnalyticsHubTour,
  executiveReservationsTour,
  executiveBudgetApprovalsTour,
  executiveOutletBudgetsTour,
  executiveBudgetMonitorTour,
  executiveBudgetIncreaseTour,
} from './executive';
import {
  ownerHomeTour,
  ownerCashPositionTour,
  ownerApprovalsTour,
  ownerBriefingTour,
  ownerAIAssistantTour,
  ownerDigestSettingsTour,
} from './owner';
import {
  hrHomeTour,
  hrPayrollTour,
  hrAdvancesTour,
  hrLeavesTour,
  hrJobApplicationsTour,
  hrJobListingsTour,
  hrServiceChargeTour,
  hrIncentiveTour,
  hrCompensationHubTour,
  hrVoucherTour,
  hrFOCTour,
  hrLBFundTour,
} from './hr';
import { generalNavigationTour, approvalCenterTour, myApprovalsTour } from './shared';

export const tourRegistry = {
  // ==== Outlet ====
  "outlet-home": outletHomeTour,
  "outlet-daily-orders": outletDailyOrdersHubTour,
  "outlet-end-of-day": outletEndOfDayWorkflowTour,
  "outlet-crm-hub": outletCRMHubTour,
  "outlet-reservation-list": outletReservationListTour,
  "outlet-reservation-form": outletReservationFormTour,
  "outlet-daily-sales": outletDailySalesTour,
  "outlet-sales-wizard": outletSalesWizardTour,
  "outlet-daily-close": outletDailyCloseTour,
  "outlet-petty-cash": outletPettyCashTour,
  "outlet-loyalty-scan": outletLoyaltyScanTour,
  "outlet-loyalty-redeem": outletLoyaltyScanTour,
  "outlet-urgent-purchase": outletUrgentPurchaseTour,
  "outlet-budget-tracker": outletBudgetTrackerTour,
  "outlet-stock-check": outletStockCheckTour,
  "outlet-stock-transfers": outletStockTransfersTour,
  "outlet-usage-log": outletUsageLogTour,
  "outlet-loyalty-points": outletLoyaltyPointsTour,

  // ==== Admin ====
  "admin-home": adminHomeTour,
  "admin-master-data": adminMasterDataHubTour,
  "admin-cms-studio": adminCMSStudioTour,
  "admin-menu-cms": adminMenuCMSTour,
  "admin-cms-brands": adminCMSStudioTour,
  "admin-cms-news": adminCMSStudioTour,
  "admin-users": adminUsersTour,
  "admin-roles": adminRolesTour,
  "admin-approval-builder": adminApprovalBuilderTour,
  "admin-workflows": adminWorkflowsTour,
  "admin-bulk-import": adminBulkImportTour,
  "admin-number-series": adminNumberSeriesTour,
  "admin-tax-config": adminTaxConfigTour,
  "admin-operations": adminOperationsTour,
  "admin-settings": adminSettingsTour,
  "admin-loyalty-overview": adminLoyaltyOverviewTour,
  "admin-loyalty-customers": adminLoyaltyCustomersTour,
  "admin-loyalty-rewards": adminLoyaltyRewardsTour,
  "admin-configuration": adminConfigurationTour,
  "admin-report-schedules": adminReportSchedulesTour,
  "admin-data-management": adminDataManagementTour,
  "admin-smart-seo": adminSmartSEOTour,
  "admin-integrations": adminIntegrationsTour,
  "admin-audit-log": adminAuditLogTour,
  "admin-tour-analytics": adminTourAnalyticsTour,
  "admin-user-management": adminUserManagementHubTour,
  "admin-setup": adminSetupHubTour,
  "admin-effective-dating": adminEffectiveDatingTour,
  "admin-loyalty-redemptions": adminLoyaltyRedemptionsTour,

  // ==== Procurement ====
  "procurement-home": procurementHomeTour,
  "procurement-kanban": procurementKanbanTour,
  "procurement-pr-list": procurementPRListTour,
  "procurement-po-list": procurementPOListTour,
  "procurement-gr": procurementGRTour,
  "procurement-vendor-compare": procurementVendorCompareTour,
  "procurement-vendors": procurementVendorsTour,
  "procurement-vendor-scorecard": procurementVendorScorecardTour,
  "procurement-vendor-recommend": procurementVendorRecommendTour,
  "procurement-rfq": procurementRFQTour,
  "procurement-consolidation": procurementConsolidationTour,
  "procurement-po-comparison": procurementPOComparisonTour,
  "procurement-price-intelligence": procurementPriceIntelligenceTour,
  "procurement-vendor-catalog": procurementVendorCatalogTour,

  // ==== Finance ====
  "finance-home": financeHomeTour,
  "finance-validation": financeValidationTour,
  "finance-manual-journal": financeManualJournalTour,
  "finance-ap": financeAPTour,
  "finance-journals": financeJournalsTour,
  "finance-payment-requests": financePaymentRequestsTour,
  "finance-payments": financePaymentsTour,
  "finance-bank-recon": financeBankReconTour,
  "finance-ar": financeARInvoicesTour,
  "finance-trial-balance": financeTrialBalanceTour,
  "finance-balance-sheet": financeBalanceSheetTour,
  "finance-cashflow": financeCashflowTour,
  "finance-coa": financeCOATour,
  "finance-profit-loss": financeProfitLossTour,
  "finance-anomalies": financeAnomaliesTour,
  "finance-comparatives": financeComparativesTour,
  "finance-periods": financePeriodsLockingTour,
  "finance-period-closing": financePeriodClosingHubTour,
  "finance-payments-hub": financePaymentsHubTour,
  "finance-reports-hub": financeReportsHubTour,
  "finance-tax-hub": financeTaxHubTour,
  "finance-budget-hub": financeBudgetHubTour,
  "finance-assets": financeAssetsTour,
  "finance-cash-position": financeCashPositionTour,
  "finance-vendor-scorecard": financeVendorScorecardTour,
  "finance-reservation-deposits": financeReservationDepositsTour,
  "finance-payment-runs": financePaymentRunsTour,
  "finance-payment-run-templates": financePaymentRunTemplatesTour,
  "finance-forecasting": financeForecastingTour,
  "finance-budget-vs-actual": financeBudgetVsActualTour,
  "finance-efaktur": financeEFakturTour,
  "finance-ebupot": financeEBupotTour,

  // ==== Inventory ====
  "inventory-home": inventoryHomeTour,
  "inventory-balance": inventoryBalanceTour,
  "inventory-movements": inventoryMovementsTour,
  "inventory-opname": inventoryOpnameTour,
  "inventory-transfers": inventoryTransfersTour,
  "inventory-adjustment": inventoryAdjustmentTour,
  "inventory-movements-hub": inventoryMovementsHubTour,
  "inventory-low-stock": inventoryLowStockTour,
  "inventory-market-list": inventoryMarketListTour,
  "inventory-valuation": inventoryValuationTour,

  // ==== Executive ====
  "executive-home": executiveHomeTour,
  "executive-owner-home": executiveOwnerHomeTour,
  "executive-outlet-drilldown": executiveOutletDrilldownTour,
  "executive-brand-drilldown": executiveBrandDrilldownTour,
  "executive-ai-qa": executiveAIQATour,
  "executive-anomaly": executiveAnomalyTour,
  "executive-brand-mix": executiveBrandMixTour,
  "executive-profit-walk": executiveProfitWalkTour,
  "executive-period-compare": executivePeriodCompareTour,
  "executive-analytics-hub": executiveAnalyticsHubTour,
  "executive-reservations": executiveReservationsTour,
  "executive-budget-approvals": executiveBudgetApprovalsTour,
  "executive-outlet-budgets": executiveOutletBudgetsTour,
  "executive-budget-monitor": executiveBudgetMonitorTour,
  "executive-budget-increase": executiveBudgetIncreaseTour,

  // ==== Owner ====
  "owner-home": ownerHomeTour,
  "owner-cash": ownerCashPositionTour,
  "owner-approvals": ownerApprovalsTour,
  "owner-briefing": ownerBriefingTour,
  "owner-ai-assistant": ownerAIAssistantTour,
  "owner-digest-settings": ownerDigestSettingsTour,

  // ==== HR ====
  "hr-home": hrHomeTour,
  "hr-payroll": hrPayrollTour,
  "hr-advances": hrAdvancesTour,
  "hr-leaves": hrLeavesTour,
  "hr-job-applications": hrJobApplicationsTour,
  "hr-job-listings": hrJobListingsTour,
  "hr-service-charge": hrServiceChargeTour,
  "hr-incentive": hrIncentiveTour,
  "hr-compensation": hrCompensationHubTour,
  "hr-voucher": hrVoucherTour,
  "hr-foc": hrFOCTour,
  "hr-lb-fund": hrLBFundTour,

  // ==== General ====
  "general-navigation": generalNavigationTour,
  "approval-center": approvalCenterTour,
  "my-approvals": myApprovalsTour,
};


// ============================================================
// TOUR VERSIONS
// ============================================================
export const TOUR_VERSIONS = {
  // Outlet
  "outlet-home": 1,
  "outlet-daily-orders": 1,
  "outlet-end-of-day": 1,
  "outlet-crm-hub": 2,
  "outlet-reservation-list": 2,
  "outlet-reservation-form": 2,
  "outlet-daily-sales": 1,
  "outlet-sales-wizard": 1,
  "outlet-daily-close": 1,
  "outlet-petty-cash": 1,
  "outlet-loyalty-scan": 1,
  "outlet-loyalty-redeem": 1,
  "outlet-urgent-purchase": 1,
  "outlet-budget-tracker": 1,
  "outlet-stock-check": 1,
  "outlet-stock-transfers": 1,
  "outlet-usage-log": 1,
  "outlet-loyalty-points": 1,

  // Admin
  "admin-home": 1,
  "admin-master-data": 1,
  "admin-cms-studio": 1,
  "admin-menu-cms": 2,
  "admin-cms-brands": 1,
  "admin-cms-news": 1,
  "admin-users": 1,
  "admin-roles": 1,
  "admin-approval-builder": 1,
  "admin-workflows": 1,
  "admin-bulk-import": 1,
  "admin-number-series": 1,
  "admin-tax-config": 1,
  "admin-operations": 1,
  "admin-settings": 1,
  "admin-loyalty-overview": 1,
  "admin-loyalty-customers": 1,
  "admin-loyalty-rewards": 1,
  "admin-configuration": 1,
  "admin-report-schedules": 1,
  "admin-data-management": 1,
  "admin-smart-seo": 1,
  "admin-integrations": 1,
  "admin-audit-log": 1,
  "admin-tour-analytics": 1,
  "admin-user-management": 1,
  "admin-setup": 1,
  "admin-effective-dating": 1,
  "admin-loyalty-redemptions": 1,

  // Procurement
  "procurement-home": 1,
  "procurement-kanban": 1,
  "procurement-pr-list": 2,
  "procurement-po-list": 2,
  "procurement-gr": 2,
  "procurement-vendor-compare": 1,
  "procurement-vendors": 1,
  "procurement-vendor-scorecard": 1,
  "procurement-vendor-recommend": 1,
  "procurement-rfq": 1,
  "procurement-consolidation": 1,
  "procurement-po-comparison": 1,
  "procurement-price-intelligence": 1,
  "procurement-vendor-catalog": 1,

  // Finance
  "finance-home": 1,
  "finance-validation": 1,
  "finance-manual-journal": 1,
  "finance-ap": 2,
  "finance-journals": 2,
  "finance-payment-requests": 1,
  "finance-payments": 2,
  "finance-bank-recon": 1,
  "finance-ar": 1,
  "finance-trial-balance": 1,
  "finance-balance-sheet": 1,
  "finance-cashflow": 1,
  "finance-coa": 1,
  "finance-profit-loss": 2,
  "finance-anomalies": 1,
  "finance-comparatives": 1,
  "finance-periods": 1,
  "finance-period-closing": 1,
  "finance-payments-hub": 1,
  "finance-reports-hub": 1,
  "finance-tax-hub": 1,
  "finance-budget-hub": 1,
  "finance-assets": 1,
  "finance-cash-position": 1,
  "finance-vendor-scorecard": 1,
  "finance-reservation-deposits": 1,
  "finance-payment-runs": 1,
  "finance-payment-run-templates": 1,
  "finance-forecasting": 1,
  "finance-budget-vs-actual": 1,
  "finance-efaktur": 1,
  "finance-ebupot": 1,

  // Inventory
  "inventory-home": 1,
  "inventory-balance": 2,
  "inventory-movements": 2,
  "inventory-opname": 2,
  "inventory-transfers": 2,
  "inventory-adjustment": 1,
  "inventory-movements-hub": 1,
  "inventory-low-stock": 1,
  "inventory-market-list": 1,
  "inventory-valuation": 1,

  // Executive
  "executive-home": 1,
  "executive-owner-home": 1,
  "executive-outlet-drilldown": 1,
  "executive-brand-drilldown": 1,
  "executive-ai-qa": 1,
  "executive-anomaly": 1,
  "executive-brand-mix": 1,
  "executive-profit-walk": 1,
  "executive-period-compare": 1,
  "executive-analytics-hub": 1,
  "executive-reservations": 1,
  "executive-budget-approvals": 1,
  "executive-outlet-budgets": 1,
  "executive-budget-monitor": 1,
  "executive-budget-increase": 1,

  // Owner
  "owner-home": 1,
  "owner-cash": 1,
  "owner-approvals": 1,
  "owner-briefing": 1,
  "owner-ai-assistant": 1,
  "owner-digest-settings": 1,

  // HR
  "hr-home": 1,
  "hr-payroll": 1,
  "hr-advances": 1,
  "hr-leaves": 1,
  "hr-job-applications": 1,
  "hr-job-listings": 1,
  "hr-service-charge": 1,
  "hr-incentive": 1,
  "hr-compensation": 1,
  "hr-voucher": 1,
  "hr-foc": 1,
  "hr-lb-fund": 1,

  // General
  "general-navigation": 1,
  "approval-center": 1,
  "my-approvals": 1,
};

export function getTourVersion(tourId) {
  return TOUR_VERSIONS[tourId] || 1;
}
