/** navigationSchema/hr.js — Hr portal navigation. */

import {
  LayoutDashboard,
  Users,
  Building2,
  Package,
  Settings,
  FileText,
  ScrollText,
  CreditCard,
  Calculator,
  FileCheck,
  Calendar,
  Banknote,
  Receipt,
  TrendingUp,
  Wallet,
  UserCog,
  DollarSign,
  Gift,
  ClipboardList,
  ShoppingCart,
  Truck,
  Store,
  BarChart3,
  Boxes,
  ArrowLeftRight,
  ClipboardCheck,
  WrenchIcon,
  Crown,
  Sparkles,
  Brain,
  MessageSquare,
  Shield,
  Activity,
  Star,
  AlertTriangle,
  Layers,
  BookOpen,
  Archive,
  Target,
  Workflow,
  Coffee,
  ListChecks,
  History,
  BellRing,
  ChevronRight,
  Landmark,
  LineChart,
  PiggyBank,
  QrCode,
  FileSpreadsheet,
  CalendarCheck,
} from "lucide-react";

// eslint-disable-next-line no-unused-vars
export const hrNav = {
  id: "hr",
  name: "HR Portal",
  sections: [
    {
      id: "dashboard",
      name: "Dashboard",
      icon: LayoutDashboard,
      items: [
        { id: "leave-requests", name: "Leave Requests", path: "/hr/leaves", icon: "CalendarDays" },
        { id: "my-approvals", name: "Approval Center", path: "/hr/approvals", icon: "CheckCircle" },
        { id: "overview", name: "Overview", path: "/hr" },
        { id: "comp-hub", name: "Compensation Hub", path: "/hr/compensation", icon: "DollarSign", badge: "HUB" },
      ],
    },
    {
      id: "hr-config",
      name: "Recruitment & Config",
      icon: WrenchIcon,
      items: [
        // REMOVED: Employees (duplikat dengan Admin → Master Data)
        { id: "job-listings", name: "Kelola Lowongan", path: "/hr/job-listings", icon: "Briefcase" },
        { id: "job-applications", name: "Lamaran Kerja", path: "/hr/job-applications", icon: "Users" },
      ],
    },
    // REMOVED: Compensation & Benefits section (single-item hub) - moved to Dashboard
  ],
};
